Map<String, String> get arabicMap => {
      "Dark Theme": "مظهر داكن",
      "Categories": "الفئات",
      "Settings": "الأعدادات",
      "Category": "الفئة",
      "Optional": "اختباري",
      "From": "من",
      "Until": "الى",
      "Forever": "الأبد",
      "Weekly": "اسبوعي",
      "Monthly": "شهري",
      "Yearly": "سنوي",
      "Daily": "يومي",
      "day": "يوم",
      "week": "اسبوع",
      "month": "شهر",
      "year": "سنة",
      "Choose date": "اختر تاريخ",
      "Today": "اليوم",
      "Add List": "اضافة قائمة",
      "Expired": "منتهي الصلاحية",
      "Notes": "ملاحضات",
      "Almost Done": "سننتهي قريبا",
      "Remove this Task?": "هل تريد حذف هذه المهمة؟",
      "THIS MONTH": "هذا الشهر",
      "Please enter The name": "الرجاء ادخال الاسم",
      "Description": "الوصف",
      "Overview": "نظرة عامة",
      "Done": "تم",
      "Final Step": "اخر خطوة",
      "Repeat every": "اعادة كل",
      "No": "لا",
      "DELETE": "حذف",
      "To": "الى",
      "Yes": "نعم",
      "Change App Language": "تغيير لغة التطبيق",
      "Arabic": "العربية",
      "Info": "معلومات",
      "Language": "اللغة",
      "January": "كانون الثاني",
      "February": "شباط",
      "March": "اذار",
      "April": "نيسان",
      "May": "ايار",
      "June": "حزيران",
      "July": "تموز",
      "August": "اب",
      "september": "أيلول",
      "October": "تشرين أول",
      "November": "تشرين ثاني",
      "December": "كانون أول",
      "Change": "تغيير",
      "Report": "تقرير",
      "First": "أول",
      "Second": "ثاني",
      "Third": "ثالث",
      "Forth": "رابع",
      "Week": "الاسبوع",
      "Due in Tommorow": "مستحق غدا",
      "Due in": "مستحق بعد",
      "days": "أيام",
      "Repeat till": "تكرار الى",
      "Preferences": "التفضيلات",
      "Calendar": "التقويم",
      "clear Complete": "مسح المكتملة",
      "Color": "اللون",
      "Priority": "الاهمية",
      "Creat Task": "انشاء مهمة",
      "Notification": "التنبيه",
      "Notifications": "التنبيهات",
      "Creat New Task": "انشاء مهمة جديدة",
      "Theme": "المظهر",
      "Tasks": "المهام",
      "Title": "عنوان",
      "All Tasks": "كل المهام",
      "Work Time": "وقت العمل",
      "Break Time": "وقت الاستراحة",
      "Start": "البدء",
      "Pause": "أيقاف مؤقت",
      "Stop": "ايقاف",
      "Pomodoro": "مؤقت",
      "Tomorrow": "غداً",
      "Other": "اخرى",
      "Task name": "اسم المهمة",
      "Task note": "معلومات اضافية عن المهمة",
      "high": "عالية",
      "medium": "متوسطة",
      "low": "منخفضة",
      "priority": "أولوية",
      "Date-Time": "الوقت والتاريخ",
      "Create Task": "انشاء المهمة",
      "Please enter the title": "الرجاء ادخال العنوان",
      "Due date": "وقت الانتهاء",
      "Work": "العمل",
      "Finished": "منتهي",
      "Personal": "شخصي",
      "work": "العمل",
      "finished": "منتهي",
      "personal": "شخصي",
      "There is no tasks here yet": "لايوجد هنا مهمات بعد.",
      "none": "بدون",
      "Default": "الافتراضي",
      "No description": "لا يوجد وصف",
      "Later": "لاحقا",
      "Task Details": "تفاصيل المهمة",
      "Save Changes": "حفظ التغييرات",
      "Delete": "حذف",
      "My Lists": "قوائمي",
      "Are you sure?": "هل أنت متأكد؟",
      "All tasks from the list will also be deleted.":
          "كل المهام المرتبطة بهذة القئمة سيتم حذفها ايضا.",
      "eg. Whishlist": "مثلا: قائمة الاماني",
      "SAVE": "حفظ",
      "List name": "اسم القائمة",
      "CANCEL": "الغاء",
    };
